### ISSUE TITLE
Invistigate a structure to represent the different parts of the generators

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#160]
Trouver une structure pour representer 
- les connections entre les différentes parties du générateurs (façade, OSC...)
- les connections entre générateurs

Propositions: command pattern
https://wiki.c2.com/?DecoratorPattern https://en.wikipedia.org/wiki/Database-centric_architecture
https://wiki.c2.com/?CommandPattern

**Comment by simondemeule** [comment]
Working on this as it turns out this is necessary for #75 and #118 because of some challenges posed by giving access to the generators from a `QQuickItem` created in QML. I am working on creating a singleton class `AppModel` that consolidates all app data. #155 and #157 will come as a free bonus of implementing this.

**Comment by simondemeule** [comment]
This is now done as of ec83480. This is on a branch that has a lot of code that partially implements #75. I have a version of this without the lattice code on cc11165. I'll have to figure out how to rebase / merge in a way that makes sense since a lot of changes happened since I started working on this.
