### ISSUE TITLE
Confirm, update and finalize the SNN parameter names, ranges of value and initial values

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#185]
- Rename the SNN's "time scale" parameter to "speed" and adjust the range of values.
- Have "network type" drop down menu to select between "Grid" and "Random" 
- Have a slider to choose the "number of connections"
- Have a slider to choose the "learning connections"
- Change inhibitory portion to percentage ?
- Change decay time to ms (not scalar) ?
- Adjust the value ranges

Remarks:
- Parameter values: For the beta we are gonna use a range of value larger than the final one so that we can do testing. The final ranges will be optimized in a later task.

<img width="1276" alt="Screenshot_21_08_2020_12_19" src="https://user-images.githubusercontent.com/3448675/90939335-6b8c8100-e3d9-11ea-8f85-8e896a5c2d3f.png">

**Comment by lucidism** [comment]
I was actually in favor of micro-rack visual structuring some time ago, when I proposed #97, but with recent design developments, we could instead group fields into "sections" and stack them all in one page with consequent separators, instead of having them in separate views, which would obstruct ease of use, I think. something along the lines of this could probably work:
![Parameters rack](https://user-images.githubusercontent.com/34627009/91072549-aecc3700-e607-11ea-8baa-24d66e388cb5.png)

**Comment by alx-s** [comment]
@lucidism that's pretty elegant!
Instead of "flags" it would be "learning".
It means the racks would be different for each type of generator,but if that's not a headache to deal with it looks like a good way to guide users into using the parameters.

**Comment by aalex** [comment]
Let's close it, for now. We might open individual tickets related to the items listed in this, if necessary.
