### ISSUE TITLE
Propose an updated sketch of the interface

### ISSUE THREAD

**Issue by alx-s** [Xmodal/autonomX#237]
Create an updated sketch of the interface. We keep the interface o release 0.1 and only modify the elements below

## Criteria
- remove the generator type button and reorganise the section #235
- add a re-init button #184
- add a reset parameters #236
- add "save," "save as," and "load" project buttons #227 
- remove the possibility to change the generator name (we always keep the one generated by default at the time of creation)
- replace the "add" button with a drop down menu button that has the list of generator that can be added in this "github" style : https://images.app.goo.gl/yiWMJrpyzDtkQNsx8
- add a set OSC speed #192

**Comment by netherwaves** [comment]
i'm going to propose further adjustments to the generator type --> generator info section:
- along with the name field, **the generator description will also become static**. the field previously containing the description will be renamed to "Patch Notes" (name open to suggestions) and serve as a place to enter any additional information relative to the user's specific generator setup;
- **the help rack will also likely need some changes**. i was thinking of moving it into the generator info rack, perhaps as a retractable sub-rack, a tooltip or a pop-up (we'll see), instead of having it as a dedicated section, which, in retrospect, turns out to be a bit of an overload on the global rack view

i'll provide a preliminary sketch by the end of the day to outline the suggestions above.

EDIT: here is the mockup below. you'll notice that there is a new "Full documentation" (again, prone to change) sub-rack, and that it now inherits the collapsing functionality from the main rack component. by default, this specific sub-rack will be retracted; for the sake of clarity, it's been expanded in the mockup.
<img width="550" alt="Generator settings rack" src="https://user-images.githubusercontent.com/34627009/113517580-c466ef00-954e-11eb-8d39-d4eadc05cfe6.png">

**Comment by alx-s** [comment]
@netherwaves instead of "patch notes" maybe "user comment" ( to avoid introducing new terms like "patch" )

**Comment by netherwaves** [comment]
here's the mockup proposition with all aforementioned changes:
![Main screen@2x](https://user-images.githubusercontent.com/34627009/113956979-6d7e4580-97ec-11eb-9dee-d495a81ce21c.png)

and here's what the CPU usage dropdown expands into:
<img width="240" alt="CPU usage - Open@2x" src="https://user-images.githubusercontent.com/34627009/113957031-84bd3300-97ec-11eb-8e77-b9a10ddd6de4.png">

suggestions are more than welcome :)

ADDENDUM 1: project name defaults to "untitled" or "unsaved project" or whatever placeholder title we agree on

**Comment by alx-s** [comment]
@netherwaves looks great!
