### ISSUE TITLE
Document the current OSC API

### ISSUE THREAD

**Issue by aalex** [Xmodal/autonomX#249]
Document the current OSC API

Blocks #234

Blocked by #255 

## Criteria
- Create an OSC.md file in the project's source code about the current OSC API.
- Describe the OSC paths it sends, and the types of its arguments.
- Describe the OSC paths it can receive, and the types of its arguments.
- Each generator has potentially different arguments it can send and receive.
- In the README, we should mention the OSC.md file.

## Details
What are the inputs and outputs per generator?
Each generator type will have different outputs and inputs.

- Generators
- Outputs
- Inputs

Example of such an OSC.md file: https://github.com/mapmapteam/mapmap/blob/develop/OSC

You can ask @alx-s for how to send/receive messages to/from AutonomX.

@alx-s can write the doc, and then someone else can verify that info and add it in the repository.

Do a `git grep sendOscData`

**Comment by alx-s** [comment]
As of release 0.1, the OSC works as follow:

Each generator possesses its individual OSC input and output that can be configured in the "OSC SETTINGS" tab in the parameters section of the generator (right side of the interface). 
You can specify the port numbers and addresses of the incoming and outgoing messages as well as the host of the outgoing messages. 
OSC messages sent by autonomX are composed of four floats that correspond to each one of the four output rectangles of the central lattice (reddish rectangle).
OSC messages sent to autonomX should be composed of four floats that correspond to each ones of the four input rectangles of the central lattice (blueish rectangles). 

The OSC messages are in the form of:
- output: ```/output <out1> <out2> <out3> <out4>```
- input: ```/input <in1> <in2> <in3> <in4>```

Warning: each generator should have unique ports for its OSC input and output. By default, new generators are given the same port numbers and therefore do not send nor receive OSC. Make sure to set unique port numbers for each new generator. (a fix to this issue is in progress)
