### ISSUE TITLE
Recursively manage layout display of a generator's parameters between C++ and QML

### ISSUE THREAD

**Issue by netherwaves** [Xmodal/autonomX#96]
**Is your feature request related to a problem? Please describe.**
Generator parameters are currently hardcoded, both in the back- and front-end sides of the app. As we add more models with completely different parameter schemes, this method will eventually be very cost-heavy, poorly scalable and hard to maintain.

**Describe the solution you'd like**
We would need to create an appropriate structure that allows to bridge a generator's editable parameters with its associated interface components in the GUI.
For example, a member property of `Generator` defined as an array of `struct Parameter`s, which would fill in info such as parameter name, data type, page index, etc., could be created, populated in each generator subclass and dynamically implemented as QObject properties.
Incidentally, the QML would accept a list of such structs and generate the Params rack accordingly, properly hooking the field with its respective C++ property on each instance.

**Comment by simondemeule** [comment]
@lucidism would you mind giving a slightly more complete description? I'm not exactly sure what this means

**Comment by lucidism** [comment]
@simondemeule I edited the original post with a more precise example of what I imagined for this enhancement. to be fair, this is mostly problematic on the QML side of things: depending on how many models we end up adding to this application, having to develop a distinct Params rack for each and every model is, in my opinion, not a great design choice and wholly unsustainable in the long run, hence the idea of refocusing a Generator's parameter properties into a common center, so QML can easily access it and generate consequent GUI elements without too much unnecessary spaghetti code.

unless I'm wrong, I would assume that this is what initially motivated your implementation of the `Facade` class, which, from what I understand, manages property binding through key-value mapping (via QQmlPropertyMap). while that is EXACTLY what I had in mind on the C++ side, QML management remains, since everything is still hardcoded in `ParamsRack.qml`. so for the most part, that's the problem I was trying to point out. hopefully this clears up any confusion with the previous issue edit!

**Comment by simondemeule** [comment]
@lucidism thanks for the detailed info. 

What initially motivated the development of the `Facade` class is actually a technical issue related to threading which requires a duplication of the `Generator` class. QML can only access `QObject`s that exist on the GUI thread, but giving `ComputeEngine` its own `QThread` requires that all the objects it accesses be assigned to that thread. This contradicts the first requirement. To work around this, a `Facade` is created on the GUI thread for each `Generator` in the `ComputeEngine` thread, automatically generating a `QObject` that has all the `QProperties` that `Generator` has, and connecting any changes to or from the `Facade` to the true `Generator`. It acts as an alias, or a placeholder that allows indirect interaction with the `Generator` object and solves the threading problem.

If we want to implement what you describe, we'd need a way to store some kind of metadata that precisely describes how each property should be edited (ie: what UI element to use, what value ranges are allowable, the description text for that UI element, its ordering on the GUI, whether the ui element needs update lag, and whether that parameter is enabled or disabled by some other parameter). It would allow us to centralize all the code necessary to create a `Generator` (or really any kind of object editable through a collection of UI elements), but it would be non-trivial to implement. 

I feel like there is actually a risk of over-engineering here, as it doesn't reduce the amount of work we have to do, it only changes the workflow, and it actually makes it more rigid and convoluted — say we want some kind of custom UI feature for one specific `Generator`, we would need to modify part of this complex layout system to account for a special case — this is an issue that just doesn't exist if we stick to writing racks in QML directly, as we can just create whatever we want here. Having one `ParamsRack.qml` for each `Generator` isn't necessarily such a bad thing.

Maybe we could have @aalex or @sofian's opinons on this?
